# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    mongodb_server: "mongodb+srv://user_onur:qweqweasd@symfony-project.mbcl0.mongodb.net/symfony_database?retryWrites=true&w=majority"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Implementation'
            - '../src/Document'
            - '../src/Service'
            - '../src/Repository'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Console/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Command\ :
        resource: '../src/Command/UserRegistrationMailer.php'
        tags:
            - { name: 'console.command', command: 'app:check-new-users' }

    tester:
        class: App\Controller\QueueController
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
